on: push

jobs:
    build1:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - run: |
              mkdir out
              echo 1 > out/a.txt
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: out/*
    build:
        runs-on: ubuntu-latest
        steps:
        - run: |
              version=22.3.0
              curl https://nodejs.org/dist/v22.3.0/node-v$version.tar.gz | tar -xz
              cd node-v$version
              ./configure --partly-static
              make -j2
              ls -al
              cp out ..
        - uses: actions/upload-artifact@main
          with:
              path: out/
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
