on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://nodejs.org/dist/v22.3.0/node-v22.3.0.tar.gz | tar -xz
              node-v22.3.0
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' push -f git@bitbucket.org:chaowenguo/${GITHUB_REPOSITORY#*/}
