on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://nodejs.org/dist/v22.3.0/node-v22.3.0.tar.gz | tar -xz
              cd node-v22.3.0
              ./configure --partly-static
              make -j 2
              make install
              ls -al
