on: push

jobs:
    build1:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - run: |
              version=22.3.0
              curl https://nodejs.org/dist/v$version/node-v$version.tar.gz | tar -xz
        - uses: svenstaro/upload-release-action@master
          with:
              repo_token: ${{secrets.GITHUB_TOKEN}}
              file: node-v22.3.0/*
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - run: |
              version=22.3.0
              curl https://nodejs.org/dist/v$version/node-v$version.tar.gz | tar -xz
              cd node-v$version
              ./configure --partly-static --prefix out
              make -j2
              make install
              ls -al out
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: out/*
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
