on: push

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - run: |
              version=22.3.0
              curl https://nodejs.org/dist/v$version/node-v$version.tar.gz | tar -xz
              cd node-v$version
              ./configure --partly-static --prefix ${{github.workspace}}/nodejs
              make -j2
              make install
              cd ${{github.workspace}}
              ls -al nodejs
              tar -cjvf nodejs.tar.bz2 nodejs
        - uses: softprops/action-gh-release@master
          with:
              token: ${{secrets.GITHUB_TOKEN}}
              tag_name: 1
              files: nodejs.tar.bz2
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
